### PR TITLE
Fixes #188 - Update ruby string method to prevent traceback

### LINKED ISSUE #188: get raw folder has old ruby string method
[1] pry(#<Fog::Compute::Vsphere::Real>)> exit
Traceback (most recent call last):
	4: from fog-create.rb:49:in `<main>'
	3: from /home/chrobert/.rvm/gems/ruby-2.5.3/gems/fog-vsphere-2.5.0/lib/fog/vsphere/models/compute/server.rb:301:in `save'
	2: from /home/chrobert/.rvm/gems/ruby-2.5.3/gems/fog-vsphere-2.5.0/lib/fog/vsphere/requests/compute/create_vm.rb:29:in `create_vm'
	1: from /home/chrobert/.rvm/gems/ruby-2.5.3/gems/fog-vsphere-2.5.0/lib/fog/vsphere/requests/compute/get_folder.rb:51:in `get_raw_vmfolder'
/home/chrobert/.rvm/gems/ruby-2.5.3/gems/fog-vsphere-2.5.0/lib/fog/vsphere/requests/compute/get_folder.rb:27:in `get_raw_folder': undefined method `blank?' for "vm":String (NoMethodError)

Working on a pr for this.

### PR DESCRIPTION
**Pull request by chris1984**
@timogoebel can I get a review please? I tried to make a vm yesterday with with your gist and hit this, looking at the ruby docs .blank is not a method for a string anymore. After switching to .empty I was able to build with the script.

### CODE REVIEW

File: lib/fog/vsphere/requests/compute/get_folder.rb [hunk 1]
```diff
@@ -23,7 +23,7 @@ def get_raw_folder(path, datacenter_name_or_obj, type)
                end
 
           valid_types = %w[vm network datastore host]
-          raise ArgumentError, "#{type} is unknown" if type.blank?
+          raise ArgumentError, "#{type} is unknown" if type.empty?
```
Comment (ekohl) [inline lib/fog/vsphere/requests/compute/get_folder.rb]: `x.blank?` is a rails alias for `x.nil? || x.empty?` so you should also check for that here

**Comment by chris1984** [comment]
@timogoebel I fixed the first part of the tests complaining about the bundler version being unsupported anymore. Now I am hitting something else with the tests, I can fix that in a separate pr. I have address Ewoud's comment

**Comment by timogoebel** [comment]
Thanks, @chris1984 and @ekohl.
