### PR TITLE
Fixes #150 - Add unit_number based on the index how it was before.

### LINKED ISSUE #150: Cannot add new disk to VM when using image based to provision
Getting this when trying to add disk to image template, this has been fixed in foreman already, creating fix in fog now.

~~~
   2018-01-18T16:04:11 9055df54 [app] [W] Failed to create a compute <name> instance <name>: InvalidRequest:
 | Required property diskId is missing from data object of type VirtualMachineRelocateSpecDiskLocator
 | Required property datastore is missing from data object of type VirtualMachineRelocateSpecDiskLocator
 | while parsing serialized DataObject of type vim.vm.RelocateSpec.DiskLocator
 | at line 1, column 651
 |
 | while parsing property "disk" of static type ArrayOfVirtualMachineRelocateSpecDiskLocator
 |
 | while parsing serialized DataObject of type vim.vm.RelocateSpec
 | at line 1, column 558
 |
 | while parsing property "location" of static type VirtualMachineRelocateSpec
 |
 | while parsing serialized DataObject of type vim.vm.CloneSpec
 | at line 1, column 512
 |
 | while parsing property "cloneSpec" of static type VirtualMachineCloneSpec
 |
 | while parsing serialized DataObject of type vim.storageDrs.StoragePlacementSpec
 | at line 1, column 283
 |
 | while parsing call information for method RecommendDatastores
 | at line 1, column 177
 |
 | while parsing SOAP body
 | at line 1, column 167
 |
 | while parsing SOAP envelope
 | at line 1, column 0
 |
 | while parsing HTTP request for method recommendDatastores
 | on object of type vim.StorageResourceManager
 | at line 1, column 0
 |
 | RbVmomi::Fault: InvalidRequest:
 | Required property diskId is missing from data object of type VirtualMachineRelocateSpecDiskLocator
 | Required property datastore is missing from data object of type VirtualMachineRelocateSpecDiskLocator
 |
 | while parsing serialized DataObject of type vim.vm.RelocateSpec.DiskLocator
 | at line 1, column 651
 |
 | while parsing property "disk" of static type ArrayOfVirtualMachineRelocateSpecDiskLocator
 |
 | while parsing serialized DataObject of type vim.vm.RelocateSpec
 | at line 1, column 558
 |
 | while parsing property "location" of static type VirtualMachineRelocateSpec
 |
 | while parsing serialized DataObject of type vim.vm.CloneSpec
 | at line 1, column 512
 |
 | while parsing property "cloneSpec" of static type VirtualMachineCloneSpec
 |
 | while parsing serialized DataObject of type vim.storageDrs.StoragePlacementSpec
 | at line 1, column 283
 |
 | while parsing call information for method RecommendDatastores
 | at line 1, column 177
 |
 | while parsing SOAP body
 | at line 1, column 167
 |
 | while parsing SOAP envelope
 | at line 1, column 0
 |
 | while parsing HTTP request for method recommendDatastores
 | on object of type vim.StorageResourceManager
 | at line 1, column 0
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rbvmomi-1.11.3/lib/rbvmomi/connection.rb:63:in `parse_response'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rbvmomi-1.11.3/lib/rbvmomi/connection.rb:92:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rbvmomi-1.11.3/lib/rbvmomi/basic_types.rb:213:in `_call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rbvmomi-1.11.3/lib/rbvmomi/basic_types.rb:76:in `block (2 levels) in init'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-vsphere-1.13.1/lib/fog/vsphere/requests/compute/vm_clone.rb:657:in `vm_clone'
 | /usr/share/foreman/app/models/compute_resources/foreman/model/vmware.rb:498:in `clone_vm'
 | /usr/share/foreman/app/models/compute_resources/foreman/model/vmware.rb:432:in `create_vm'
~~~

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@timogoebel same with this one, can we get this into the new version?

File: lib/fog/vsphere/requests/compute/vm_clone.rb [hunk 1]
```diff
@@ -803,6 +804,7 @@ def modify_template_volumes_specs(vm_mob_ref, volumes)
                          device: template_volume }
             end
           end
+          new_volumes.map { |volume| volume.unit_number = volumes.index(volume) }
```
Comment (timogoebel) [inline lib/fog/vsphere/requests/compute/vm_clone.rb]: I believe this is a bit too naive. I believe we have to skip unit number 7 since the pvscsi driver reserves SCSI ID 7.

**Comment by timogoebel** [comment]
Thanks, @chris1984.
