### PR TITLE
Fixes #201 - added disks on vm cloning

### LINKED ISSUE #201: Create storagePod disks correctly while cloning
As of now, adding more disk to the storagePod will fail on cloning the VM.

### PR DESCRIPTION
**Pull request by ezr-ondrej**
If more disks are specified and their placement is on storagePod, cloning fails.
This is a partial fix though, because now if storagePod is specified, it places all the disks on that pod, no matter what the disks have specified.
It will clone the machine successfuly though.

### CODE REVIEW

**Comment by chris1984** [comment]
This will also allow me to add another unit test to the image testing for regression tests ;)

File: lib/fog/vsphere/requests/compute/vm_clone.rb [hunk 1]
```diff
@@ -789,14 +789,17 @@ def modify_template_nics_specs(vm_mob_ref, nics, datacenter)
           specs
         end
 
-        def modify_template_volumes_specs(vm_mob_ref, volumes)
+        def modify_template_volumes_specs(vm_mob_ref, volumes, default_storage_pod = nil)
```
Comment (timogoebel) [inline lib/fog/vsphere/requests/compute/vm_clone.rb]: can we make this a kwarg so it's easier to figure out what the method expects?

File: lib/fog/vsphere/requests/compute/vm_clone.rb [hunk 2]
```diff
@@ -789,14 +789,17 @@ def modify_template_nics_specs(vm_mob_ref, nics, datacenter)
...
           template_volumes = vm_mob_ref.config.hardware.device.grep(RbVmomi::VIM::VirtualDisk)
           modified_volumes = volumes.take(template_volumes.size)
           new_volumes      = volumes.drop(template_volumes.size)
 
           specs = []
           template_volumes.zip(modified_volumes).each do |template_volume, new_volume|
             if new_volume
+              # copy identifiers fo fog device to mark them as used
```
Comment (timogoebel) [inline lib/fog/vsphere/requests/compute/vm_clone.rb]: typo: `to fog`

File: lib/fog/vsphere/requests/compute/vm_clone.rb [hunk 3]
```diff
@@ -811,8 +814,7 @@ def modify_template_volumes_specs(vm_mob_ref, volumes)
                          device: template_volume }
             end
           end
-          new_volumes.map { |volume| volume.unit_number = volumes.index(volume) < 7 ? volumes.index(volume) : volumes.index(volume) + 1 }
```
Comment (timogoebel) [inline lib/fog/vsphere/requests/compute/vm_clone.rb]: This is solved by copying the identifiers from the template volume?

Comment (ezr-ondrej) [reply lib/fog/vsphere/requests/compute/vm_clone.rb]: Yeah exactly, the problem was the volume numbers were duplicated, but the above line is fixing it.

File: lib/fog/vsphere/requests/compute/vm_clone.rb (hunk 2 above)
Comment (ezr-ondrej) [reply lib/fog/vsphere/requests/compute/vm_clone.rb]: :dart:

File: lib/fog/vsphere/requests/compute/vm_clone.rb (hunk 1 above)
Comment (ezr-ondrej) [reply lib/fog/vsphere/requests/compute/vm_clone.rb]: yeah, feels better :+1:

**Comment by chris1984** [comment]
Thanks @ezr-ondrej
